/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define ADC_BASE_ADDR 		0x40012000UL
#define ADC_CR1_REG_OFFSET 	0x04UL
#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR		0x40023800UL
#define RCC_APB2_ENR_OFFSET	0x44UL
#define RCC_APB2_ENR_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)


int main(void){

	uint32_t *pRccApb2Enr 	= (uint32_t *) RCC_APB2_ENR_ADDR;
	uint32_t *pAdcCr1Reg 	= (uint32_t *) ADC_CR1_REG_ADDR;

	// 1. Enable the peripheral clock for ADC1
	*pRccApb2Enr |= (1 << 8);
	// 2. modify the ADC cr1 register
	*pAdcCr1Reg |= (1 << 8);

	/* We want to activate ADC control register. To do that, follow the steps:
	 * 1. Go to ADC control register 1 page to collect address offset.
	 * 2. Check the base address of ADC1 in memory map.
	 * 3. Set 1 value in 8-th bit of ADC1 register using addr_offset + base_addr.
	 * 4. Check the bus of ADC1. It is APB2.
	 * 5. Go to RCC APB2 enable register.
	 * 6. Verify the position of ADC1 enable in RCC APB2 enable register. That is 8-th position.
	 * 8. Set 1 in the 8-th position of APB2 enable register BEFORE ADC control register.
	 */

	for(;;);
}
